/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DeleteController;
import Controller.FileController;
import Controller.SalaryController;
import Controller.SearchController;
import Model.CBGV;
import Model.CBGVModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84818
 */
public class Home extends javax.swing.JFrame {

    public Home() {

        this.setTitle("Quản lý giáo viên");
        initComponents();
        this.setLocationRelativeTo(null);
        panel1.setBackground(Color.WHITE);
        menu.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        pnhome.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        panel1.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        pngioithieu.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        pnluong.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        pntimkiem.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        jPanel2.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        menu.setBackground(Color.cyan);
        list_cbgv = new CBGVModel();
        deleteController = new DeleteController(this);
        searchController = new SearchController(this);
        salaryController = new SalaryController(this);
        fileController = new FileController(this);
        btnxoa.addActionListener(deleteController);
        btnsearch.addActionListener(searchController);
        btnupdate.addActionListener(salaryController);
        btnsxtang.addActionListener(salaryController);
        btnsxgiam.addActionListener(salaryController);
        btnsavefile.addActionListener(fileController);
        btnupdatefile.addActionListener(fileController);
    }
    public CBGVModel list_cbgv;
    private DeleteController deleteController;
    private SearchController searchController;
    private SalaryController salaryController;
    private FileController fileController;

    public void DeleteCBGV() {
        ImageIcon icon = new ImageIcon("Pictogrammers-Material-Account.24");
        DefaultTableModel tb = (DefaultTableModel) tblthongke.getModel();
        if (tb.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Danh sách đang rỗng!");
            return;
        }
        String maSo = (String) JOptionPane.showInputDialog(
                null,
                "Nhập mã số giáo viên cần xóa:",
                "Tìm Kiếm",
                JOptionPane.INFORMATION_MESSAGE,
                icon,
                null,
                ""
        );
        if (list_cbgv.check() == true) {
            JOptionPane.showMessageDialog(rootPane, "Danh sách đang rỗng!", "Cảnh báo", 2);
            return;
        }
        CBGV cbgv = list_cbgv.kiemTraTonTai(maSo);
        if (cbgv == null) {
            JOptionPane.showMessageDialog(rootPane, "Không tồn tại giáo viên này!");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa giáo viên này không?", "Warning", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                int len = tb.getRowCount();
                for (int i = len - 1; i >= 0; i--) {
                    String id = (String) tb.getValueAt(i, 0);
                    if (maSo.equals(id)) {
                        list_cbgv.deleteCBGV(maSo);
                        tb.removeRow(i);
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công!");
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        lbclose = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbtongquan = new javax.swing.JLabel();
        lbhome = new javax.swing.JLabel();
        lbsearch = new javax.swing.JLabel();
        lbsalary = new javax.swing.JLabel();
        lblienhe = new javax.swing.JLabel();
        btnthoat = new javax.swing.JToggleButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pngioithieu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pnhome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblthongke = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnthem = new javax.swing.JToggleButton();
        btnsua = new javax.swing.JToggleButton();
        btnxoa = new javax.swing.JToggleButton();
        btnsavefile = new javax.swing.JToggleButton();
        btnupdatefile = new javax.swing.JToggleButton();
        pntimkiem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tathongtin = new javax.swing.JTextArea();
        pnluong = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblluong = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtluongmin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtluongtb = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtluongmax = new javax.swing.JTextField();
        btnsxgiam = new javax.swing.JToggleButton();
        jLabel21 = new javax.swing.JLabel();
        txttongluong = new javax.swing.JTextField();
        btnupdate = new javax.swing.JToggleButton();
        btnsxtang = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        lbmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbclose.setBackground(new java.awt.Color(0, 255, 255));
        lbclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icons8-Windows-8-Programming-Delete-Sign.32.png"))); // NOI18N
        lbclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbclose.setOpaque(true);
        lbclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbcloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbcloseMouseExited(evt);
            }
        });
        menu.add(lbclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
        menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, -1));
        menu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 487, 250, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText(".DnCoder");
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        lbtongquan.setBackground(new java.awt.Color(0, 255, 255));
        lbtongquan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbtongquan.setText("Tổng quan");
        lbtongquan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbtongquan.setOpaque(true);
        lbtongquan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtongquanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbtongquanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbtongquanMouseExited(evt);
            }
        });
        menu.add(lbtongquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        lbhome.setBackground(new java.awt.Color(0, 255, 255));
        lbhome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbhome.setText("Trang chủ");
        lbhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbhome.setOpaque(true);
        lbhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbhomeMouseExited(evt);
            }
        });
        menu.add(lbhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        lbsearch.setBackground(new java.awt.Color(0, 255, 255));
        lbsearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbsearch.setText("Tìm kiếm");
        lbsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbsearch.setOpaque(true);
        lbsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbsearchMouseExited(evt);
            }
        });
        menu.add(lbsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        lbsalary.setBackground(new java.awt.Color(0, 255, 255));
        lbsalary.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbsalary.setText("Tổng lương");
        lbsalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbsalary.setOpaque(true);
        lbsalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbsalaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbsalaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbsalaryMouseExited(evt);
            }
        });
        menu.add(lbsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        lblienhe.setBackground(new java.awt.Color(0, 255, 255));
        lblienhe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblienhe.setText("Liên hệ");
        lblienhe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblienhe.setOpaque(true);
        lblienhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblienheMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblienheMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblienheMouseExited(evt);
            }
        });
        menu.add(lblienhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        btnthoat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alecive-Flatwoken-Apps-Dialog-Shutdown.24.png"))); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthoat.setOpaque(true);
        btnthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnthoatMouseClicked(evt);
            }
        });
        menu.add(btnthoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/programmer (1).png"))); // NOI18N
        menu.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setText("Code & Fix Bugs");
        menu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, 20));

        panel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        pngioithieu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Quản Lý Giáo Viên");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Ngày phát hành:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Người lập trình:");

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField3.setText("Lê Dương Nhật");
        jTextField3.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Mã số SV:");

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField4.setText("2821104973");
        jTextField4.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Giá Bán: ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Mục đích:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Các chức năng chính:");

        jList1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Thêm", "2. Xóa", "3. Sửa", "4. Sắp Xếp" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setEnabled(false);
        jScrollPane2.setViewportView(jList1);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField5.setText("500.000 đ");
        jTextField5.setEnabled(false);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Phát triển phần mềm quản lý các thông tin\nnhư tên, tuổi, quê quán, lương của các cán bộ,\ngiáo viên.");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Ngôn ngữ sử dụng:");

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField6.setText("Java");
        jTextField6.setEnabled(false);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField7.setText("12/12/2023");
        jTextField7.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Framework:");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setText("Java Swing");
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout pngioithieuLayout = new javax.swing.GroupLayout(pngioithieu);
        pngioithieu.setLayout(pngioithieuLayout);
        pngioithieuLayout.setHorizontalGroup(
            pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pngioithieuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(126, 126, 126)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pngioithieuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(501, 501, 501))
        );
        pngioithieuLayout.setVerticalGroup(
            pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pngioithieuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel9)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addGroup(pngioithieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(pngioithieu, "card2");

        pnhome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Trang Chủ");

        tblthongke.setAutoCreateRowSorter(true);
        tblthongke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblthongke.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tblthongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ và tên", "Tuổi", "Quê quán", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblthongke.setGridColor(new java.awt.Color(255, 255, 255));
        tblthongke.getTableHeader().setResizingAllowed(false);
        tblthongke.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblthongke);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Bảng thống kê:");

        btnthem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Hopstarter-Soft-Scraps-Button-Add.24.png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnthemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnthemMouseExited(evt);
            }
        });
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Bokehlicia-Captiva-Edit.24.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Hopstarter-Sleek-Xp-Basic-Close-2.24.png"))); // NOI18N
        btnxoa.setText("Xóa");

        btnsavefile.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnsavefile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Custom-Icon-Design-Pretty-Office-7-Save.24.png"))); // NOI18N
        btnsavefile.setText("Lưu");

        btnupdatefile.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnupdatefile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Oxygen-Icons.org-Oxygen-Actions-svn-update.24.png"))); // NOI18N
        btnupdatefile.setText("Cập nhật dữ liệu");

        javax.swing.GroupLayout pnhomeLayout = new javax.swing.GroupLayout(pnhome);
        pnhome.setLayout(pnhomeLayout);
        pnhomeLayout.setHorizontalGroup(
            pnhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnhomeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnhomeLayout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnsavefile, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnhomeLayout.createSequentialGroup()
                        .addGroup(pnhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnhomeLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 712, Short.MAX_VALUE)
                                .addComponent(btnupdatefile)))
                        .addGap(108, 108, 108))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnhomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492))
        );
        pnhomeLayout.setVerticalGroup(
            pnhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnhomeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(pnhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdatefile)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(pnhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnsavefile))
                .addGap(157, 157, 157))
        );

        jPanel1.add(pnhome, "card3");

        pntimkiem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Tìm Kiếm Giáo Viên");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Nhập mã giáo viên:");

        txtsearch.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Gakuseisean-Aire-Search.24.png"))); // NOI18N
        btnsearch.setText("Tìm");
        btnsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsearchMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Thông tin:");

        tathongtin.setEditable(false);
        tathongtin.setBackground(new java.awt.Color(255, 255, 255));
        tathongtin.setColumns(20);
        tathongtin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tathongtin.setLineWrap(true);
        tathongtin.setRows(5);
        tathongtin.setTabSize(20);
        jScrollPane5.setViewportView(tathongtin);

        javax.swing.GroupLayout pntimkiemLayout = new javax.swing.GroupLayout(pntimkiem);
        pntimkiem.setLayout(pntimkiemLayout);
        pntimkiemLayout.setHorizontalGroup(
            pntimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntimkiemLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(pntimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(pntimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pntimkiemLayout.createSequentialGroup()
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(pntimkiemLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pntimkiemLayout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pntimkiemLayout.setVerticalGroup(
            pntimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntimkiemLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(pntimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(pntimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel1.add(pntimkiem, "card4");

        pnluong.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Tổng kết lương");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblluong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblluong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblluong.setGridColor(new java.awt.Color(255, 255, 255));
        tblluong.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblluong);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Tổng lương:");

        txtluongmin.setEditable(false);
        txtluongmin.setBackground(new java.awt.Color(255, 255, 255));
        txtluongmin.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Lương cao nhất:");

        txtluongtb.setEditable(false);
        txtluongtb.setBackground(new java.awt.Color(255, 255, 255));
        txtluongtb.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Lương thấp nhất:");

        txtluongmax.setEditable(false);
        txtluongmax.setBackground(new java.awt.Color(255, 255, 255));
        txtluongmax.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btnsxgiam.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnsxgiam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pictogrammers-Material-Sort-alphabetical-descending.24.png"))); // NOI18N
        btnsxgiam.setText("Sắp xếp giảm");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Trung bình lương:");

        txttongluong.setEditable(false);
        txttongluong.setBackground(new java.awt.Color(255, 255, 255));
        txttongluong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btnupdate.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Graphicloads-100-Flat-Upload.24.png"))); // NOI18N
        btnupdate.setText("Cập nhật dữ liệu");

        btnsxtang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnsxtang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pictogrammers-Material-Sort-alphabetical-ascending.24.png"))); // NOI18N
        btnsxtang.setText("Sắp xếp tăng");

        javax.swing.GroupLayout pnluongLayout = new javax.swing.GroupLayout(pnluong);
        pnluong.setLayout(pnluongLayout);
        pnluongLayout.setHorizontalGroup(
            pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnluongLayout.createSequentialGroup()
                .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnluongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsxtang)
                        .addGap(91, 91, 91)
                        .addComponent(btnsxgiam)
                        .addGap(120, 120, 120))
                    .addGroup(pnluongLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate))
                        .addGap(79, 79, 79)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtluongmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnluongLayout.createSequentialGroup()
                        .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtluongmax, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtluongtb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttongluong, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnluongLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(486, 486, 486))
        );
        pnluongLayout.setVerticalGroup(
            pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnluongLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtluongmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtluongmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtluongtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(63, 63, 63)
                .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txttongluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 112, Short.MAX_VALUE))
            .addGroup(pnluongLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnluongLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnupdate)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsxgiam)
                            .addComponent(btnsxtang))
                        .addGap(92, 92, 92))
                    .addGroup(pnluongLayout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addGap(19, 19, 19))))
        );

        jPanel1.add(pnluong, "card5");

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1150, 540));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        lbmenu.setBackground(new java.awt.Color(255, 255, 255));
        lbmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Amitjakhu-Drip-Menu.32 (1).png"))); // NOI18N
        lbmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbmenu.setOpaque(true);
        lbmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbmenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbmenu)
                .addContainerGap(1112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 100));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcloseMouseClicked
        closeMenu();
    }//GEN-LAST:event_lbcloseMouseClicked

    private void lbcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcloseMouseEntered
        labelcolor(lbclose);
    }//GEN-LAST:event_lbcloseMouseEntered

    private void lbcloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcloseMouseExited

        resetcolor(lbclose);
    }//GEN-LAST:event_lbcloseMouseExited

    private void lbmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbmenuMouseExited
        resetcolor1(lbmenu);
    }//GEN-LAST:event_lbmenuMouseExited

    private void lbmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbmenuMouseEntered
        labelcolor1(lbmenu);
    }//GEN-LAST:event_lbmenuMouseEntered

    private void lbmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbmenuMouseClicked
        openMenu();
    }//GEN-LAST:event_lbmenuMouseClicked

    private void lbtongquanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtongquanMouseClicked
        lbcloseMouseClicked(evt);
        resetcolor(lbhome);
        pngioithieu.setVisible(true);
        pnhome.setVisible(false);
        pntimkiem.setVisible(false);
        pnluong.setVisible(false);
    }//GEN-LAST:event_lbtongquanMouseClicked

    private void lbhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbhomeMouseClicked
        lbcloseMouseClicked(evt);
        pnhome.setVisible(true);
        pngioithieu.setVisible(false);
        pntimkiem.setVisible(false);
        pnluong.setVisible(false);
    }//GEN-LAST:event_lbhomeMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        DefaultTableModel tb = (DefaultTableModel) tblthongke.getModel();
        if (tb.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng cập nhật dữ liệu mới nhất từ tệp trước khi thêm mới!", "Thông báo", 0);
            return;

        }
        addForm();

    }//GEN-LAST:event_btnthemActionPerformed
    public void addForm() {
        new AddForm(this, rootPaneCheckingEnabled, list_cbgv).setVisible(rootPaneCheckingEnabled);
    }
    private void lbtongquanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtongquanMouseEntered

        labelcolor(lbtongquan);
    }//GEN-LAST:event_lbtongquanMouseEntered

    private void lbtongquanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtongquanMouseExited
        resetcolor(lbtongquan);
    }//GEN-LAST:event_lbtongquanMouseExited

    private void lbhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbhomeMouseEntered
        labelcolor(lbhome);
    }//GEN-LAST:event_lbhomeMouseEntered

    private void lbhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbhomeMouseExited
        resetcolor(lbhome);
    }//GEN-LAST:event_lbhomeMouseExited

    private void btnthemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemMouseEntered
        btnthem.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnthemMouseEntered

    private void btnthemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemMouseExited
        btnthem.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnthemMouseExited

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        DefaultTableModel tb = (DefaultTableModel) tblthongke.getModel();
        if (tblthongke.getSelectedRow() != -1) {
            new AddForm(this, rootPaneCheckingEnabled, list_cbgv).update();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn dòng cần sửa đổi!", "Thông báo", 0);
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void lbsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbsearchMouseClicked
        lbcloseMouseClicked(evt);
        pntimkiem.setVisible(true);
        pngioithieu.setVisible(false);
        pnhome.setVisible(false);
        pnluong.setVisible(false);


    }//GEN-LAST:event_lbsearchMouseClicked

    private void lbsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbsearchMouseEntered
        labelcolor(lbsearch);
    }//GEN-LAST:event_lbsearchMouseEntered

    private void lbsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbsearchMouseExited
        resetcolor(lbsearch);
    }//GEN-LAST:event_lbsearchMouseExited

    private void lbsalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbsalaryMouseClicked
        lbcloseMouseClicked(evt);
        pnluong.setVisible(true);
        pntimkiem.setVisible(false);
        pngioithieu.setVisible(false);
        pnhome.setVisible(false);
    }//GEN-LAST:event_lbsalaryMouseClicked

    private void lbsalaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbsalaryMouseEntered
        labelcolor(lbsalary);
    }//GEN-LAST:event_lbsalaryMouseEntered

    private void lbsalaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbsalaryMouseExited
        resetcolor(lbsalary);
    }//GEN-LAST:event_lbsalaryMouseExited

    private void btnsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseClicked
        String searchText = txtsearch.getText();
        if (searchText == null || searchText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã giáo viên!", "Thông báo", 0);
        }

    }//GEN-LAST:event_btnsearchMouseClicked

    private void btnthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthoatMouseClicked
        int option = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btnthoatMouseClicked

    private void lblienheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblienheMouseClicked

        String message = "<html><b>Nếu bạn có bất kỳ câu hỏi gì, xin vui lòng liên hệ với:</b><br>"
                + "Số điện thoại: <font color='blue'>0818938562</font><br>"
                + "Email: <font color='blue'>nhatnhatnhatle@gmail.com</font></html>";
        JOptionPane.showMessageDialog(rootPane, message, "Thông tin liên hệ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblienheMouseClicked

    private void lblienheMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblienheMouseExited
        resetcolor(lblienhe);
    }//GEN-LAST:event_lblienheMouseExited

    private void lblienheMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblienheMouseEntered
        labelcolor(lblienhe);
    }//GEN-LAST:event_lblienheMouseEntered
    private void labelcolor(JLabel label) {
        label.setBackground(new java.awt.Color(255, 255, 255));
    }

    private void resetcolor(JLabel label) {
        label.setBackground(new java.awt.Color(0, 255, 255));
    }

    private void labelcolor1(JLabel label) {
        label.setBackground(new java.awt.Color(220, 220, 220));
    }

    private void resetcolor1(JLabel label) {
        label.setBackground(new java.awt.Color(255, 255, 255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnsavefile;
    public javax.swing.JToggleButton btnsearch;
    private javax.swing.JToggleButton btnsua;
    private javax.swing.JToggleButton btnsxgiam;
    private javax.swing.JToggleButton btnsxtang;
    private javax.swing.JToggleButton btnthem;
    private javax.swing.JToggleButton btnthoat;
    public javax.swing.JToggleButton btnupdate;
    private javax.swing.JToggleButton btnupdatefile;
    private javax.swing.JToggleButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lbclose;
    private javax.swing.JLabel lbhome;
    private javax.swing.JLabel lblienhe;
    private javax.swing.JLabel lbmenu;
    private javax.swing.JLabel lbsalary;
    private javax.swing.JLabel lbsearch;
    private javax.swing.JLabel lbtongquan;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel pngioithieu;
    private javax.swing.JPanel pnhome;
    private javax.swing.JPanel pnluong;
    private javax.swing.JPanel pntimkiem;
    public javax.swing.JTextArea tathongtin;
    public javax.swing.JTable tblluong;
    public javax.swing.JTable tblthongke;
    public javax.swing.JTextField txtluongmax;
    public javax.swing.JTextField txtluongmin;
    public javax.swing.JTextField txtluongtb;
    public javax.swing.JTextField txtsearch;
    public javax.swing.JTextField txttongluong;
    // End of variables declaration//GEN-END:variables

    private void openMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 232; i++) {
                    menu.setSize(i, 620);
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    private void closeMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 232; i > 0; i--) {
                    menu.setSize(i, 620);
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }



}
